engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  rubocop:
    enabled: false
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- vendor/**/*
