sudo: false
before_install:
  - gem update --system
  - gem install bundler
  - gem --version
  - bundle --version
script:  rake travis:ci
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.0
branches:
  only:
    - master
addons:
  code_climate:
    repo_token: 5bd70aa7d70fc8ce3a649a0a05c0119e9441fa174964c0a270c6e952bc75996d
